export enum ApplicationDataEnum {
  productCategory = 1,
  unitOfMeasurement = 2,
  taxOption = 3,
  classCategory = 4,
  serviceCategory = 5,
  title = 6,
  contactCategory = 7,
  patientStatus = 8,
  patientPosition = 9,
  patientClassification = 10,
  patientRelationship = 11,
  patientOccupation = 12,
  cardType = 13,
  healthFundName = 14,
  supplier = 15,
  employer = 16,
  Medicare = 17,
  DVA = 18,
  BreakName = 1000,
}
